### ISSUE TITLE
Playback not working

### ISSUE THREAD

**Issue by HellboundGlory** [museofficial/muse#1069]
**What's happening?**
When I tell the bot to play a song it joins the vc and loads the song but it stays at 00:00 on the time and there is nothing playing

**Logs**

```

```

**Screenshots**

![image](https://github.com/user-attachments/assets/a868a453-b63f-4270-9554-c549592f7683)

**Runtime**
I'm running Muse:
- [YES] Directly from the cloned repository
- [NO] Inside a Docker container

**Versions**
- Muse: v2.9.1
- Docker (if applicable): NA
- OS: Windows 11 x64
- Node.js: 20.16.0
- ffmpeg: 7.0.2

**Comment by jedichrome** [comment]
This is happening to me as well-- except I'm using docker.

**Comment by Docanis** [comment]
> This is happening to me as well-- except I'm using docker.

+1 to this, i can play music streams from spotify like lofi girl but not songs with a start/end.

**Comment by Hazzajenko** [comment]
> **Versions**
> 
> * Muse: v2.9.1

This should be fixed in the latest version (v2.9.3)


> This is happening to me as well-- except I'm using docker.

> > This is happening to me as well-- except I'm using docker.
> 
> +1 to this, i can play music streams from spotify like lofi girl but not songs with a start/end.

Try the latest docker image `ghcr.io/museofficial/muse:latest`

**Comment by Ryah** [comment]
I just had this issue, and changing the docker image in the docker compose file and then repulling it worked for me.

Check if your logs show something like "yt-dl out of date" or something like that. If it does, you're not on the latest version. At least that's the only thing that's changed on my end log wise.

**Comment by mayonegai** [comment]
It also does not work for me. Docker on version 2.9.3

```
muse-1  | 2024-08-22T09:34:56.684Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
muse-1  | 2024-08-22T09:34:56.685Z muse Cache miss: [{"searchParams":{"part":"id, snippet, contentDetails","id":"3ah4t1P9yFA"}}]
muse-1  | 2024-08-22T09:34:56.737Z muse HTTPError: Response code 403 (Forbidden)
muse-1  |     at Request.<anonymous> (file:///usr/app/node_modules/got/dist/source/as-promise/index.js:86:42)
muse-1  |     at Object.onceWrapper (node:events:632:26)
muse-1  |     at Request.emit (node:events:529:35)
muse-1  |     at Request._onResponseBase (file:///usr/app/node_modules/got/dist/source/core/index.js:691:22)
muse-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
muse-1  |     at async Request._onResponse (file:///usr/app/node_modules/got/dist/source/core/index.js:730:13)
```

**Comment by jrjrau** [comment]
> It also does not work for me. Docker on version 2.9.3

Looks like an issue with your youtube API key, I'd double check all the API keys are active and try again

**Comment by Docanis** [comment]
> > **Versions**
> > 
> > * Muse: v2.9.1
> 
> This should be fixed in the latest version (v2.9.3)
> 
> > This is happening to me as well-- except I'm using docker.
> 
> > > This is happening to me as well-- except I'm using docker.
> > 
> > 
> > +1 to this, i can play music streams from spotify like lofi girl but not songs with a start/end.
> 
> Try the latest docker image `ghcr.io/museofficial/muse:latest`

I was using some old docker image updating to this docker image fixed it for me.

**Comment by krussedull** [comment]
same problem , fresh install windows.. cant undefen

**Comment by simawn** [comment]
I had the same problem and it got fixed after I pulled the latest Docker image

**Comment by jrjrau** [comment]
>cant undefen

The bot is deafened intentionally, there are no voice activated commands (yet) so it does not need to hear you.

**Comment by ARCKNIGHT117** [comment]
I just set mine up and I am running directly on windows node 18.20.4 

I am having similar issues sometimes and sometimes getting "Output format webm is not available"

**Comment by xxtensazenxx** [comment]
Same issue here - it joins, posts the link to the youtube video its playing and it just never starts.
The bot has been broken for over a month for me and I'm seeing no help from the dev.
Is this project dead?

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
