### ISSUE TITLE
Bot crashes when playing specific video

### ISSUE THREAD

**Issue by Nystrata** [museofficial/muse#1082]
**What's happening?**
When a certain video is played, the entire bot crashes when it tries to play it: https://www.youtube.com/watch?v=TXhL0phuX8c
Other videos work fine

**Logs**

```
muse-1  | /usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152
muse-1  |                       throw new DiscordAPIError(data, 'code' in data ? data.code : data.error, status, method, url, requestData);                                                                      
muse-1  |                             ^
muse-1  |
muse-1  |
muse-1  | DiscordAPIError[50006]: Cannot send an empty message
muse-1  |     at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)                                                                                  
muse-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
muse-1  |     at SequentialHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:399:20)                                                       
muse-1  |     at SequentialHandler.queueRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/handlers/SequentialHandler.ts:169:11)                                                     
muse-1  |     at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)                                                                                             
muse-1  |     at async VoiceChannel.send (/usr/app/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:162:15)                                                                                 
muse-1  |     at default.onAudioPlayerIdle (/usr/app/src/services/player.ts:591:9) {
muse-1  |   requestBody: {
muse-1  |     files: [],
muse-1  |     json: {
muse-1  |       content: undefined,
muse-1  |       tts: false,                                                                                                                                                                                      
muse-1  |       nonce: undefined,
muse-1  |       embeds: [],
muse-1  |       components: undefined,
muse-1  |       username: undefined,
muse-1  |       avatar_url: undefined,
muse-1  |       allowed_mentions: undefined,
muse-1  |       flags: undefined,
muse-1  |       message_reference: undefined,
muse-1  |       attachments: undefined,
muse-1  |       sticker_ids: undefined,
muse-1  |       thread_name: undefined
muse-1  |     }
muse-1  |   },
muse-1  |   rawError: { message: 'Cannot send an empty message', code: 50006 },
muse-1  |   code: 50006,
muse-1  |   status: 400,
muse-1  |   method: 'POST',
muse-1  |   url: 'https://discord.com/api/v10/channels/<id>/messages'
muse-1  | }
muse-1  |
```
**Screenshots**
It does manage to display a now-playing before it crashes
![image](https://github.com/user-attachments/assets/8ea2f40d-e0e4-4de4-9e01-8469616aceba)

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: `Running version 2.9.3 built on 8/19/2024 (commit 1e17b94321744ffbe4a6176a900286a834c952d1)`
- Docker (if applicable): `Docker version 27.1.1, build 6312585`
- OS: Description:  `Ubuntu 24.04 LTS`
- Node.js: (if running outside the Docker container): N/A
- ffmpeg: (if running outside the Docker container, 4.1 or later is required): N/A

**Comment by ITESaurabh** [comment]
+1 same occurred to me also

**Comment by Nystrata** [comment]
Pulled the latest: 
Running version 2.10.0 built on 11/4/2024 (commit 716d6d9f4f2cd1a6872e463e9877203a259478a3)

And the video now plays now
