### ISSUE TITLE
Invalid define value

### ISSUE THREAD

**Issue by GFSKGaming** [museofficial/muse#1083]
**What's happening?**
Whenever the bot launches, it immediately halts with these errors.

**Logs**

```
npm run start

> muse@2.9.3 start
> npm run env:set-database-url -- tsx src/scripts/migrate-and-start.ts


> muse@2.9.3 env:set-database-url
> tsx src/scripts/run-with-database-url.ts tsx src/scripts/migrate-and-start.ts

(node:23916) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: Transform failed with 1 error:
error: Invalid define value (must be an entity name or valid JSON syntax): 'file:///D:/GFSK's%20Music%20Bot/muse/node_modules/dotenv/lib/main.js'
    at failureErrorWithLog (D:\GFSK's Music Bot\muse\node_modules\esbuild\lib\main.js:1624:15)
    at D:\GFSK's Music Bot\muse\node_modules\esbuild\lib\main.js:1413:29
    at D:\GFSK's Music Bot\muse\node_modules\esbuild\lib\main.js:678:9
    at handleIncomingPacket (D:\GFSK's Music Bot\muse\node_modules\esbuild\lib\main.js:775:9)
    at Socket.readFromStdout (D:\GFSK's Music Bot\muse\node_modules\esbuild\lib\main.js:644:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: "Invalid define value (must be an entity name or valid JSON syntax): 'file:///D:/GFSK's%20Music%20Bot/muse/node_modules/dotenv/lib/main.js'"
    }
  ],
  warnings: []
}
```

**Screenshots**

**Additional context**
This is a fresh install if it matters.

**Runtime**
I'm running Muse:
- [✔] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: v2.93
- OS: Windows 10 Pro (Build 19041.vb_release.191206-1406)
- Node.js: v19.3.0
- ffmpeg: 7.0.2 (I believe)

**Comment by TiagoGrosso** [comment]
@GFSKGaming did you setup your env file?

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
