### ISSUE TITLE
Not a valid value

### ISSUE THREAD

**Issue by Coraz97** [museofficial/muse#1114]
**What's happening?**
Whenever I try to add a song with a link, the bot tells me it's not a valid value. Searching via text works as intended

**Logs**
Nothing suspicious here, just some Sponsorblock errors
```
Could not fetch skip segments for "YF1eYbfbH5k" : ResponseError: [SponsorBlock] Not Found
    at Object.statusCheck (/usr/app/node_modules/sponsorblock-api/lib/api/utils.js:50:19)
    at SponsorBlock.<anonymous> (/usr/app/node_modules/sponsorblock-api/lib/api/impl/user.js:40:21)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/app/node_modules/sponsorblock-api/lib/api/impl/user.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
```

**Screenshots**
![Discord_2024-10-25_17-35-49](https://github.com/user-attachments/assets/76e27b7d-e0f3-4386-ab0b-69392097c4d2)

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.9.4
- Docker (if applicable): 27.3.1
- OS: Debian 12 Bookwom

**Comment by Coraz97** [comment]
Issue seems to have fixed itself.
