### ISSUE TITLE
Bot not playing playlists? How to confirm age for age restricted songs?

### ISSUE THREAD

**Issue by GhostieSpook** [museofficial/muse#1162]
**What's happening?**
Concisely describe what's going wrong.
Friend went to play a playlist but it played the first song and didnt actually queue all 18 songs when it said it did.
I think its cause a song is age restricted but thats just by looking at the logs. How would I fix it?
**Logs**

```
Error checking for updates: Connect Timeout Error
You can disable this check by setting the `YTDL_NO_UPDATE` env variable.
/usr/app/node_modules/@distube/ytdl-core/lib/utils.js:164
    return new UnrecoverableError(playability.reason || (playability.messages && playability.messages[0]));
              ^
UnrecoverableError: Sign in to confirm your age
    at exports.playError (/usr/app/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
    at exports.getBasicInfo (/usr/app/node_modules/@distube/ytdl-core/lib/info.js:46:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: latest
- Docker (if applicable): 2.10.0
- OS:
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by GhostieSpook** [comment]
Still haven't found a fix. Any response would help greatly!

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
