### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by quintinmintiens** [museofficial/muse#455]
I'm trying to build on a Ubuntu docker container, i did it before without any issue but now this error occurs

```

56       adapterCreator: channel.guild.voiceAdapterCreator,
         ~~~~~~~~~~~~~~

  node_modules/@discordjs/voice/dist/index.d.ts:1526:5
    1526     adapterCreator: DiscordGatewayAdapterCreator;
             ~~~~~~~~~~~~~~
    The expected type comes from property 'adapterCreator' which is declared here on type 'JoinVoiceChannelOptions & CreateVoiceConnectionOptions'


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! muse@0.2.1 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the muse@0.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-30T11_03_50_058Z-debug.log


```

![error](https://user-images.githubusercontent.com/75444661/147746527-bd41b5df-8a85-46d2-9e1c-103d27f4a1b6.png)

**Comment by quintinmintiens** [comment]
The error log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle muse@0.2.1~prebuild: muse@0.2.1
6 info lifecycle muse@0.2.1~build: muse@0.2.1
7 verbose lifecycle muse@0.2.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle muse@0.2.1~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/h>9 verbose lifecycle muse@0.2.1~build: CWD: /home/bots/muse
10 silly lifecycle muse@0.2.1~build: Args: [ '-c', 'tsc' ]
11 silly lifecycle muse@0.2.1~build: Returned: code: 2  signal: null
12 info lifecycle muse@0.2.1~build: Failed to exec build script
13 verbose stack Error: muse@0.2.1 build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:>13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn>13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid muse@0.2.1
15 verbose cwd /home/bots/muse
16 verbose Linux 5.10.0-9-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 2
22 error muse@0.2.1 build: `tsc`
22 error Exit status 2
23 error Failed at the muse@0.2.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by codetheweb** [comment]
I'm guessing your Node version is too old. Try upgrading to v16.

**Comment by shiftybitshiftr** [comment]
Closing this as part of the support backlog cleanup. This report has not been updated in over a year and predates the current playback/voice/runtime stack. Please open a fresh issue if it still reproduces on v2.11.3 or newer, and include the startup `Running version ...` line, image tag/digest or install method, host architecture, the exact URL/query/command, and fresh logs.
